<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class SyncDesignTokens extends Command
{
    protected $signature = 'design:sync-tokens {--source=resources/design-tokens.json : Path to tokens JSON} {--out=public/build/design-tokens.css : Output CSS file} {--dry : Preview without writing file}';

    protected $description = 'Transform design tokens JSON into CSS custom properties file.';

    public function handle(): int
    {
        $fs = new Filesystem();
        $source = $this->option('source');
        $out = $this->option('out');
        $dry = $this->option('dry');

        if (!$fs->exists($source)) {
            if ($fs->exists('resources/design-tokens.example.json')) {
                $this->warn("Source not found: {$source}. Using example file instead.");
                $source = 'resources/design-tokens.example.json';
            } else {
                $this->error("Tokens file not found: {$source}");
                return self::FAILURE;
            }
        }

        $raw = json_decode($fs->get($source), true);
        if (!$raw || !is_array($raw)) {
            $this->error('Invalid JSON structure.');
            return self::FAILURE;
        }

        $lines = [];
        $lines[] = '/* Auto-generated by design:sync-tokens at ' . now()->toDateTimeString() . ' */';
        $lines[] = ':root {';

        // Color tokens (support nested shade objects)
        if (!empty($raw['color'])) {
            $lines[] = '  /* Color */';
            foreach ($raw['color'] as $group => $value) {
                if (is_array($value)) {
                    foreach ($value as $k => $v) {
                        if (is_string($v)) {
                            $lines[] = '  --pd-color-' . Str::slug($group . '-' . $k) . ': ' . $v . ';';
                        }
                    }
                }
            }
        }

        // Typography
        if (!empty($raw['typography'])) {
            $lines[] = '  /* Typography */';
            foreach ($raw['typography'] as $name => $spec) {
                if (!is_array($spec)) continue;
                foreach ($spec as $attr => $v) {
                    $lines[] = '  --pd-typography-' . Str::slug($name . '-' . $attr) . ': ' . $v . (is_numeric($v) ? (in_array($attr, ['fontSize','lineHeight']) ? 'px' : '') : '') . ';';
                }
            }
        }

        // Radius
        if (!empty($raw['radius'])) {
            $lines[] = '  /* Radius */';
            foreach ($raw['radius'] as $name => $v) {
                $lines[] = '  --pd-radius-' . Str::slug($name) . ': ' . $v . (is_numeric($v) ? 'px' : '') . ';';
            }
        }

        // Spacing (array of scale values)
        if (!empty($raw['spacing']) && is_array($raw['spacing'])) {
            $lines[] = '  /* Spacing */';
            foreach ($raw['spacing'] as $i => $v) {
                $idx = $i + 1; // start at 1
                $lines[] = '  --pd-spacing-' . $idx . ': ' . $v . (is_numeric($v) ? 'px' : '') . ';';
            }
        }

        // Elevation (shadows)
        if (!empty($raw['elevation'])) {
            $lines[] = '  /* Elevation */';
            foreach ($raw['elevation'] as $name => $v) {
                $lines[] = '  --pd-shadow-' . Str::slug($name) . ': ' . $v . ';';
            }
        }

        // Opacity
        if (!empty($raw['opacity'])) {
            $lines[] = '  /* Opacity */';
            foreach ($raw['opacity'] as $name => $v) {
                $lines[] = '  --pd-opacity-' . Str::slug($name) . ': ' . $v . ';';
            }
        }

        // Motion
        if (!empty($raw['motion'])) {
            $lines[] = '  /* Motion */';
            foreach ($raw['motion'] as $name => $v) {
                $lines[] = '  --pd-motion-' . Str::slug($name) . ': ' . $v . ';';
            }
        }

        $lines[] = '}';

        $css = implode(PHP_EOL, $lines) . PHP_EOL;

        if ($dry) {
            $this->line($css);
            return self::SUCCESS;
        }

        // Ensure directory
        $dir = dirname($out);
        if (!$fs->exists($dir)) {
            $fs->makeDirectory($dir, 0755, true);
        }

        $fs->put($out, $css);
        $this->info("Tokens synced → {$out}");

        return self::SUCCESS;
    }
}
