<?php

declare(strict_types=1);

namespace App\Services;

use App\Jobs\SendWhatsAppMessage;
use App\Models\ConsolidatedReport;
use App\Models\CustomerSurvey;
use App\Models\Sample;
use App\Models\TestRequest;
use App\Models\WhatsAppMessageBatch;
use App\Models\WhatsAppMessageLog;
use App\Repositories\SettingsRepository;
use App\Services\WhatsApp\TemplateService;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class ConsolidatedReportService
{
    public const DEFAULT_SIGNERS_STRUCTURE = [
        ['role' => 'Pembuat', 'name' => '', 'position' => '', 'nip' => ''],
        ['role' => 'Pemeriksa', 'name' => '', 'position' => '', 'nip' => ''],
        ['role' => 'Pengesah', 'name' => '', 'position' => '', 'nip' => ''],
    ];

    public function __construct(
        private readonly ActiveSubstanceService $activeSubstanceService,
        private readonly IkuService $ikuService,
        private readonly SettingsRepository $settings,
        private readonly TemplateService $templateService
    ) {}

    /**
     * Get consolidated report data for preview.
     */
    public function getPreviewData(string $periodType, Carbon $start, Carbon $end): array
    {
        return [
            'period_label' => $this->getPeriodLabel($periodType, $start, $end),
            'statistics' => $this->getStatisticsForPeriod($start, $end),
            'active_substances' => $this->getActiveSubstancesForPeriod($start, $end),
            'processing_time' => $this->getProcessingTimeBreakdown($start, $end),
            'satisfaction' => $this->getSatisfactionBreakdown($start, $end),
            'gender' => $this->getGenderBreakdown($start, $end),
            'jurisdiction' => $this->getJurisdictionBreakdown($start, $end),
            'age_range' => $this->getAgeRangeBreakdown($start, $end),
            'iku' => $periodType === 'quarterly' ? $this->ikuService->computeForPeriod($start, $end) : null,
            'comparison' => $this->getComparisonData($periodType, $start),
            'narratives' => $this->getDefaultNarratives($periodType),
            'signers' => $this->getDefaultSigners(),
        ];
    }

    /**
     * Generate and save report.
     */
    public function generate(array $data, ?int $userId = null, bool $isAutoGenerated = false): ConsolidatedReport
    {
        $start = Carbon::parse($data['period_start']);
        $end = Carbon::parse($data['period_end']);
        $periodType = $data['period_type'];

        // Calculate period label for narrative replacement
        $periodLabel = $this->getPeriodLabel($periodType, $start, $end);

        // Process narratives to replace placeholders
        $narratives = $data['narratives'];
        if (isset($narratives['opening'])) {
            $narratives['opening'] = str_replace('{period_label}', $periodLabel, $narratives['opening']);
        }
        if (isset($narratives['closing'])) {
            $narratives['closing'] = str_replace('{period_label}', $periodLabel, $narratives['closing']);
        }

        // Prepare data structure
        $reportData = [
            'statistics' => $this->getStatisticsForPeriod($start, $end),
            'active_substances' => $this->getActiveSubstancesForPeriod($start, $end),
            'processing_time' => $this->getProcessingTimeBreakdown($start, $end),
            'satisfaction' => $this->getSatisfactionBreakdown($start, $end),
            'gender' => $this->getGenderBreakdown($start, $end),
            'jurisdiction' => $this->getJurisdictionBreakdown($start, $end),
            'age_range' => $this->getAgeRangeBreakdown($start, $end),
            'iku' => $periodType === 'quarterly' ? $this->ikuService->computeForPeriod($start, $end) : null,
        ];

        $comparisonData = $this->getComparisonData($periodType, $start);

        // Create database record
        $report = ConsolidatedReport::create([
            'period_type' => $periodType,
            'period_start' => $start,
            'period_end' => $end,
            'period_label' => $this->getPeriodLabel($periodType, $start, $end),
            'report_data' => $reportData,
            'comparison_data' => $comparisonData,
            'narrative_sections' => $narratives,
            'signers' => $data['signers'],
            'generated_by' => $userId,
            'generated_at' => now(),
            'is_auto_generated' => $isAutoGenerated,
        ]);

        // Generate PDF
        $this->generatePdf($report);

        return $report;
    }

    /**
     * Get statistics for a specific period.
     */
    public function getStatisticsForPeriod(Carbon $start, Carbon $end): array
    {
        $requestsReceived = TestRequest::whereBetween('created_at', [$start, $end])->count();

        // FIX: Only count requests that are truly completed (picked up by investigator)
        // Status 'ready_for_delivery' means lab is done but NOT yet picked up
        // Status 'completed' or 'delivered' means actually picked up
        $requestsCompleted = TestRequest::whereIn('status', ['completed', 'delivered'])
            ->whereBetween('completed_at', [$start, $end])
            ->count();

        $samplesReceived = Sample::whereBetween('created_at', [$start, $end])->count();

        // FIX: Use robust logic from IkuService to handle null testing_completed_at & legacy status
        $samplesTested = Sample::whereIn('sample_status', [
            'ready_for_delivery',
            'interpretation_done',
            'tested',      // Legacy status
            'completed',   // Legacy status
        ])
            ->where(function ($query) use ($start, $end) {
                $query->whereBetween('testing_completed_at', [$start, $end])
                    ->orWhere(function ($q) use ($start, $end) {
                        $q->whereNull('testing_completed_at')
                            ->whereBetween('updated_at', [$start, $end]);
                    });
            })
            ->count();

        // LHU Terbit = Jumlah sampel dari request yang siap diambil pada periode tersebut
        // Setiap sampel menghasilkan satu LHU
        $lhuIssued = Sample::whereHas('testRequest', function ($query) use ($start, $end) {
            $query->whereNotNull('ready_for_delivery_at')
                ->whereBetween('ready_for_delivery_at', [$start, $end]);
        })->count();

        // Calculate average processing time (days)
        // FIX: Calculate from submitted_at to ready_for_delivery_at (weekdays only)
        $processingTimes = TestRequest::whereIn('status', ['completed', 'ready_for_delivery', 'delivered'])
            ->whereNotNull('ready_for_delivery_at')
            ->whereBetween('ready_for_delivery_at', [$start, $end])
            ->get()
            ->map(function ($req) {
                $startDate = $req->submitted_at ?? $req->created_at;
                $endDate = $req->ready_for_delivery_at;

                if (! $startDate || ! $endDate || $endDate->lt($startDate)) {
                    return 0;
                }

                return $startDate->diffInWeekdays($endDate);
            });

        $avgProcessingTime = (float) ($processingTimes->avg() ?? 0);

        // Calculate average satisfaction rating
        // FIX: Cast to float to avoid round() errors
        $avgSatisfaction = (float) (CustomerSurvey::whereBetween('submitted_at', [$start, $end])
            ->avg('score_avg') ?? 0);

        return [
            'total_requests_received' => $requestsReceived,
            'total_requests_completed' => $requestsCompleted,
            'total_samples_received' => $samplesReceived,
            'total_samples_tested' => $samplesTested,
            'total_lhu_issued' => $lhuIssued,
            'avg_processing_days' => round($avgProcessingTime, 1),
            'satisfaction_rating' => round($avgSatisfaction, 1),
        ];
    }

    /**
     * Get active substance breakdown for a specific period.
     */
    public function getActiveSubstancesForPeriod(Carbon $start, Carbon $end): array
    {
        // Use case-insensitive grouping to merge "tramadol" and "Tramadol" into one entry
        // LOWER() ensures consistent grouping regardless of input case
        $substances = Sample::whereBetween('created_at', [$start, $end])
            ->whereNotNull('active_substance')
            ->select(
                DB::raw('LOWER(TRIM(active_substance)) as normalized_substance'),
                DB::raw('count(*) as total')
            )
            ->groupBy(DB::raw('LOWER(TRIM(active_substance))'))
            ->orderByDesc('total')
            ->get();

        $totalSamples = $substances->sum('total');
        $items = [];

        foreach ($substances as $item) {
            // Normalize display name: "tramadol" -> "Tramadol"
            $displayName = ucwords(strtolower(trim($item->normalized_substance)));

            $items[] = [
                'name' => $displayName,
                'count' => $item->total,
                'percentage' => $totalSamples > 0 ? round(($item->total / $totalSamples) * 100, 1) : 0,
            ];
        }

        return [
            'items' => $items,
            'total' => $totalSamples,
        ];
    }

    /**
     * Get processing time breakdown for a period.
     */
    public function getProcessingTimeBreakdown(Carbon $start, Carbon $end): array
    {
        $requests = TestRequest::whereIn('status', ['completed', 'ready_for_delivery', 'delivered'])
            ->whereNotNull('ready_for_delivery_at')
            ->whereBetween('ready_for_delivery_at', [$start, $end])
            ->get()
            ->map(function ($req) {
                $startDate = $req->submitted_at ?? $req->created_at;
                $endDate = $req->ready_for_delivery_at;

                if (! $startDate || ! $endDate || $endDate->lt($startDate)) {
                    return 0;
                }

                return $startDate->diffInWeekdays($endDate);
            });

        $total = $requests->count();

        $categories = [
            '≤ 3 hari' => $requests->filter(fn ($d) => $d <= 3)->count(),
            '4-7 hari' => $requests->filter(fn ($d) => $d >= 4 && $d <= 7)->count(),
            '8-14 hari' => $requests->filter(fn ($d) => $d >= 8 && $d <= 14)->count(),
            '> 14 hari' => $requests->filter(fn ($d) => $d > 14)->count(),
        ];

        return [
            'categories' => collect($categories)->map(fn ($count, $label) => [
                'label' => $label,
                'count' => $count,
                'percentage' => $total > 0 ? round(($count / $total) * 100, 1) : 0,
            ])->values()->toArray(),
            'total' => $total,
            'avg_days' => $total > 0 ? round($requests->avg(), 1) : 0,
        ];
    }

    /**
     * Get customer satisfaction breakdown for a period.
     */
    public function getSatisfactionBreakdown(Carbon $start, Carbon $end): array
    {
        $surveys = CustomerSurvey::whereBetween('submitted_at', [$start, $end])
            ->whereNotNull('score_avg')
            ->get();

        $total = $surveys->count();
        $avgScore = (float) ($surveys->avg('score_avg') ?? 0);

        // Group by rounded score (1-4)
        $ratings = [
            4 => ['label' => 'Sangat Puas (4)', 'count' => 0],
            3 => ['label' => 'Puas (3)', 'count' => 0],
            2 => ['label' => 'Kurang Puas (2)', 'count' => 0],
            1 => ['label' => 'Tidak Puas (1)', 'count' => 0],
        ];

        foreach ($surveys as $survey) {
            $rounded = (int) round((float) $survey->score_avg);
            $rounded = max(1, min(4, $rounded)); // Clamp 1-4
            $ratings[$rounded]['count']++;
        }

        return [
            'ratings' => collect($ratings)->map(fn ($r) => [
                'label' => $r['label'],
                'count' => $r['count'],
                'percentage' => $total > 0 ? round(($r['count'] / $total) * 100, 1) : 0,
            ])->values()->toArray(),
            'total_respondents' => $total,
            'avg_score' => round($avgScore, 2),
        ];
    }

    /**
     * Get suspect gender breakdown for a period.
     */
    public function getGenderBreakdown(Carbon $start, Carbon $end): array
    {
        $requests = TestRequest::whereBetween('created_at', [$start, $end])
            ->select('suspect_gender', DB::raw('count(*) as total'))
            ->groupBy('suspect_gender')
            ->get();

        // Normalize gender variations (male/female, Laki-laki/Perempuan, L/P, etc)
        $maleCount = 0;
        $femaleCount = 0;
        $unknownCount = 0;

        foreach ($requests as $req) {
            $gender = strtolower(trim($req->suspect_gender ?? ''));

            if (in_array($gender, ['l', 'laki-laki', 'laki', 'pria', 'male', 'm'])) {
                $maleCount += $req->total;
            } elseif (in_array($gender, ['p', 'perempuan', 'wanita', 'female', 'f'])) {
                $femaleCount += $req->total;
            } else {
                $unknownCount += $req->total;
            }
        }

        $total = $maleCount + $femaleCount + $unknownCount;

        $genders = [
            ['label' => 'Laki-laki', 'count' => $maleCount],
            ['label' => 'Perempuan', 'count' => $femaleCount],
            ['label' => 'Tidak Diketahui', 'count' => $unknownCount],
        ];

        return [
            'items' => collect($genders)->map(fn ($g) => [
                'label' => $g['label'],
                'count' => $g['count'],
                'percentage' => $total > 0 ? round(($g['count'] / $total) * 100, 1) : 0,
            ])->toArray(),
            'total' => $total,
        ];
    }

    /**
     * Get jurisdiction (asal user) breakdown for a period.
     */
    public function getJurisdictionBreakdown(Carbon $start, Carbon $end): array
    {
        $data = TestRequest::whereBetween('test_requests.created_at', [$start, $end])
            ->join('investigators', 'test_requests.investigator_id', '=', 'investigators.id')
            ->select('investigators.jurisdiction', DB::raw('count(*) as total'))
            ->groupBy('investigators.jurisdiction')
            ->orderByDesc('total')
            ->limit(10)
            ->get();

        $total = TestRequest::whereBetween('created_at', [$start, $end])->count();

        return [
            'items' => $data->map(fn ($item) => [
                'label' => $item->jurisdiction ?: 'Tidak Diketahui',
                'count' => $item->total,
                'percentage' => $total > 0 ? round(($item->total / $total) * 100, 1) : 0,
            ])->toArray(),
            'total' => $total,
        ];
    }

    /**
     * Get suspect age range breakdown for a period.
     */
    public function getAgeRangeBreakdown(Carbon $start, Carbon $end): array
    {
        $requests = TestRequest::whereBetween('created_at', [$start, $end])
            ->whereNotNull('suspect_age')
            ->pluck('suspect_age');

        $nullCount = TestRequest::whereBetween('created_at', [$start, $end])
            ->whereNull('suspect_age')
            ->count();

        $total = $requests->count() + $nullCount;

        $ranges = [
            '< 18 tahun' => $requests->filter(fn ($a) => $a < 18)->count(),
            '18-25 tahun' => $requests->filter(fn ($a) => $a >= 18 && $a <= 25)->count(),
            '26-35 tahun' => $requests->filter(fn ($a) => $a >= 26 && $a <= 35)->count(),
            '36-45 tahun' => $requests->filter(fn ($a) => $a >= 36 && $a <= 45)->count(),
            '46-55 tahun' => $requests->filter(fn ($a) => $a >= 46 && $a <= 55)->count(),
            '> 55 tahun' => $requests->filter(fn ($a) => $a > 55)->count(),
            'Tidak Diketahui' => $nullCount,
        ];

        return [
            'items' => collect($ranges)->map(fn ($count, $label) => [
                'label' => $label,
                'count' => $count,
                'percentage' => $total > 0 ? round(($count / $total) * 100, 1) : 0,
            ])->values()->toArray(),
            'total' => $total,
        ];
    }

    /**
     * Get comparison data with previous period.
     */
    public function getComparisonData(string $periodType, Carbon $currentStart): array
    {
        // Determine previous period range
        $prevStart = $currentStart->copy();
        $prevEnd = $currentStart->copy();

        switch ($periodType) {
            case 'biweekly':
                if ($currentStart->day <= 15) {
                    // Previous is 16-end of last month
                    $prevStart = $prevStart->subMonth()->startOfMonth()->addDays(15);
                    $prevEnd = $prevEnd->subMonth()->endOfMonth();
                } else {
                    // Previous is 1-15 of current month
                    $prevStart = $prevStart->startOfMonth();
                    $prevEnd = $prevEnd->startOfMonth()->addDays(14)->endOfDay();
                }
                break;
            case 'monthly':
                $prevStart->subMonth()->startOfMonth();
                $prevEnd->subMonth()->endOfMonth();
                break;
            case 'quarterly':
                $prevStart->subQuarter()->startOfQuarter();
                $prevEnd->subQuarter()->endOfQuarter();
                break;
        }

        $currentStats = $this->getStatisticsForPeriod($currentStart, $this->getPeriodEnd($periodType, $currentStart));
        $prevStats = $this->getStatisticsForPeriod($prevStart, $prevEnd);

        $changes = [];
        foreach ($currentStats as $key => $val) {
            $prevVal = $prevStats[$key] ?? 0;
            $diff = $val - $prevVal;

            // Avoid division by zero
            $diffPercent = $prevVal > 0 ? round(($diff / $prevVal) * 100, 1) : 0;
            if ($prevVal == 0 && $val > 0) {
                $diffPercent = 100;
            }

            $changes[$key] = [
                'previous' => $prevVal,
                'current' => $val,
                'diff' => $diff,
                'diff_percent' => $diffPercent,
            ];
        }

        return [
            'previous_period' => [
                'start' => $prevStart->toDateString(),
                'end' => $prevEnd->toDateString(),
                'label' => $this->getPeriodLabel($periodType, $prevStart, $prevEnd),
            ],
            'changes' => $changes,
        ];
    }

    /**
     * Get default narratives from settings.
     */
    public function getDefaultNarratives(string $periodType): array
    {
        return [
            'opening' => $this->settings->get('consolidated_report.default_narratives.opening', ''),
            'closing' => $this->settings->get('consolidated_report.default_narratives.closing', ''),
        ];
    }

    /**
     * Get default signers from settings.
     */
    public function getDefaultSigners(): array
    {
        $signers = $this->settings->get('consolidated_report.default_signers', null);

        if (empty($signers)) {
            return self::DEFAULT_SIGNERS_STRUCTURE;
        }

        return $signers;
    }

    /**
     * Generate PDF file and update record.
     */
    public function generatePdf(ConsolidatedReport $report): void
    {
        $pdf = Pdf::loadView('pdf.consolidated-report', ['report' => $report])
            ->setPaper('a4', 'portrait');

        $filename = "laporan-{$report->period_type}-{$report->period_start->format('Ymd')}.pdf";
        $path = "reports/consolidated/{$filename}";

        Storage::put($path, $pdf->output());

        $report->update([
            'pdf_path' => $path,
            'pdf_size' => Storage::size($path),
        ]);
    }

    private function getPeriodLabel(string $type, Carbon $start, Carbon $end): string
    {
        Carbon::setLocale('id');

        return match ($type) {
            'biweekly' => 'Bi-weekly '.$start->format('d').'-'.$end->translatedFormat('d F Y'),
            'monthly' => 'Bulan '.$start->translatedFormat('F Y'),
            'quarterly' => 'Triwulan '.$start->quarter.' Tahun '.$start->year,
            default => $start->format('d/m/Y').' - '.$end->format('d/m/Y'),
        };
    }

    private function getPeriodEnd(string $type, Carbon $start): Carbon
    {
        $end = $start->copy();

        return match ($type) {
            'biweekly' => $start->day <= 15 ? $end->startOfMonth()->addDays(14)->endOfDay() : $end->endOfMonth(),
            'monthly' => $end->endOfMonth(),
            'quarterly' => $end->endOfQuarter(),
            default => $end,
        };
    }

    /**
     * Send notification for generated report.
     */
    public function sendGenerationNotification(ConsolidatedReport $report): int
    {
        // Check if notification is enabled
        $notifyEnabled = (bool) $this->settings->get('consolidated_report.notify_on_generate', true);

        if (! $notifyEnabled) {
            return 0;
        }

        // Determine target phone
        $targetPhone = $this->settings->get('consolidated_report.notify_phone');
        if (empty($targetPhone)) {
            $targetPhone = '+6285956592404'; // Default fallback
        }

        $normalizedPhone = $this->normalizePhone((string) $targetPhone);
        $normalizedJid = $normalizedPhone.'@s.whatsapp.net';

        if ($this->hasNotificationQueuedOrSent($report, $normalizedJid)) {
            Log::info("Consolidated report notification already queued/sent for report {$report->id} to {$normalizedJid}");

            return 0;
        }

        // Format message
        $appUrl = rtrim((string) config('app.url'), '/');
        $generatedAt = $report->generated_at ? $report->generated_at->format('d/m/Y H:i') : now()->format('d/m/Y H:i');

        $templateKey = $this->resolveConsolidatedTemplateKey((string) $report->period_type);
        $message = $this->templateService->render('system', $templateKey, [
            'period_type' => (string) $report->period_type,
            'period_label' => (string) $report->period_label,
            'period_start' => $report->period_start->format('d/m/Y'),
            'period_end' => $report->period_end->format('d/m/Y'),
            'generated_at' => $generatedAt,
            'total_requests' => (string) ($report->report_data['statistics']['total_requests_received'] ?? 0),
            'total_samples' => (string) ($report->report_data['statistics']['total_samples_received'] ?? 0),
            'report_url' => "{$appUrl}/statistics?tab=reports",
        ]);

        if (trim($message) === '') {
            $message = $this->buildFallbackConsolidatedMessage($report, $generatedAt, (string) $appUrl);
        }

        try {
            // Create batch record
            $batch = WhatsAppMessageBatch::create([
                'type' => 'consolidated_report_notification',
                'source_type' => ConsolidatedReport::class,
                'source_id' => $report->id,
                'title' => "Laporan {$report->period_label}",
                'message_preview' => mb_strimwidth($message, 0, 100, '...'),
                'total_recipients' => 1,
                'sent_count' => 0,
                'failed_count' => 0,
                'mention_all' => false,
                'started_at' => now(),
                'created_by' => $report->generated_by,
            ]);

            WhatsAppMessageLog::create([
                'batch_id' => $batch->id,
                'recipient_jid' => $normalizedJid,
                'recipient_name' => $normalizedPhone,
                'recipient_type' => 'individual',
                'status' => 'pending',
            ]);

            // Dispatch job
            SendWhatsAppMessage::dispatch($normalizedPhone, $message, $batch->id);

            Log::info("Consolidated report notification queued for {$normalizedPhone}");

            return 1;
        } catch (\Exception $e) {
            Log::error("Failed to send consolidated report notification: {$e->getMessage()}");

            return 0;
        }
    }

    private function hasNotificationQueuedOrSent(ConsolidatedReport $report, string $recipientJid): bool
    {
        $reportIds = ConsolidatedReport::query()
            ->where('period_type', (string) $report->period_type)
            ->whereDate('period_start', $report->period_start->toDateString())
            ->whereDate('period_end', $report->period_end->toDateString())
            ->pluck('id');

        if ($reportIds->isEmpty()) {
            return false;
        }

        return WhatsAppMessageBatch::query()
            ->where('type', 'consolidated_report_notification')
            ->where('source_type', ConsolidatedReport::class)
            ->whereIn('source_id', $reportIds->all())
            ->whereHas('logs', function ($query) use ($recipientJid) {
                $query->where('recipient_jid', $recipientJid)
                    ->whereIn('status', ['pending', 'processing', 'sent']);
            })
            ->exists();
    }

    private function resolveConsolidatedTemplateKey(string $periodType): string
    {
        return match ($periodType) {
            'biweekly' => 'CONSOLIDATED_BIWEEKLY',
            'monthly' => 'CONSOLIDATED_MONTHLY',
            'quarterly' => 'CONSOLIDATED_QUARTERLY',
            default => 'CONSOLIDATED_BIWEEKLY',
        };
    }

    private function buildFallbackConsolidatedMessage(ConsolidatedReport $report, string $generatedAt, string $appUrl): string
    {
        $message = "📊 *LAPORAN GABUNGAN PERIODIK*\n\n";
        $message .= "Laporan {$report->period_type} periode {$report->period_label} telah di-generate.\n\n";
        $message .= "📅 Periode: {$report->period_start->format('d/m/Y')} - {$report->period_end->format('d/m/Y')}\n";
        $message .= "⏰ Waktu Generate: {$generatedAt}\n";
        $message .= '📈 Total Permintaan: '.($report->report_data['statistics']['total_requests_received'] ?? 0)."\n";
        $message .= '🧪 Total Sampel: '.($report->report_data['statistics']['total_samples_received'] ?? 0)."\n\n";
        $message .= "Silakan akses laporan di:\n";
        $message .= "{$appUrl}/statistics?tab=reports\n\n";
        $message .= "—\n";
        $message .= 'Staff Laboratorium Farmapol Pusdokkes Polri';

        return $message;
    }

    private function normalizePhone(string $phone): string
    {
        $phone = preg_replace('/[^0-9]/', '', $phone) ?? '';
        if ($phone !== '' && str_starts_with($phone, '0')) {
            $phone = '62'.substr($phone, 1);
        }

        return $phone;
    }

    /**
     * Determine if reports should be auto-generated today.
     */
    public function shouldAutoGenerate(): array
    {
        $today = Carbon::now('Asia/Jakarta');
        $reports = [];

        // Bi-weekly: Generate only on 16th (for 1-15 period)
        // Note: 16-31 is NOT auto-generated as it's covered by the monthly report
        if ($today->day === 16) {
            $reports[] = [
                'type' => 'biweekly',
                'start' => $today->copy()->startOfMonth(),
                'end' => $today->copy()->startOfMonth()->addDays(14)->endOfDay(),
            ];
        }

        if ($today->day === 1) {
            // Monthly for previous month
            $reports[] = [
                'type' => 'monthly',
                'start' => $today->copy()->subMonth()->startOfMonth(),
                'end' => $today->copy()->subMonth()->endOfMonth(),
            ];

            // Quarterly on Jan 1, Apr 1, Jul 1, Oct 1
            if (in_array($today->month, [1, 4, 7, 10])) {
                $quarterStart = $today->copy()->subQuarter()->startOfQuarter();
                $reports[] = [
                    'type' => 'quarterly',
                    'start' => $quarterStart,
                    'end' => $quarterStart->copy()->endOfQuarter(),
                ];
            }
        }

        return $reports;
    }
}
