<?php

namespace App\Services;

use App\Models\EvidenceUnit;
use App\Models\LabelPrintLog;
use App\Models\RemainingUnit;
use App\Models\Sample;
use App\Models\TestRequest;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class LabelService
{
    /**
     * Create evidence units from sample IDs.
     *
     * @param  int  $requestId  Test request ID
     * @param  array  $sampleIds  Array of sample IDs to create labels for
     * @return Collection Created EvidenceUnit records
     *
     * @throws RuntimeException if samples don't belong to request
     */
    public function createEvidenceUnits(int $requestId, array $sampleIds): Collection
    {
        $request = TestRequest::with('investigator')->findOrFail($requestId);

        // Validate all samples belong to this request
        $samples = Sample::whereIn('id', $sampleIds)
            ->where('test_request_id', $requestId)
            ->get();

        if ($samples->count() !== count($sampleIds)) {
            throw new RuntimeException('Some samples do not belong to this request.');
        }

        $created = collect();

        DB::transaction(function () use ($request, $samples, &$created) {
            foreach ($samples as $sample) {
                // Skip if evidence unit already exists for this sample
                if (EvidenceUnit::where('sample_id', $sample->id)->exists()) {
                    continue;
                }

                $receivedBy = $sample->received_by ?: Auth::id();

                $evidenceUnit = EvidenceUnit::create([
                    'request_id' => $request->id,
                    'sample_id' => $sample->id,
                    'receipt_code' => $request->receipt_number,
                    'sample_code' => $sample->sample_code,
                    'sample_type' => $sample->sample_category ?? $sample->sample_form,
                    'sample_desc' => $sample->short_description ?? $sample->sample_description,
                    'investigator_name' => $request->investigator?->name ?? $request->investigator?->rank_name,
                    'investigator_unit' => $request->investigator?->satuan_kerja ?? $request->investigator?->unit,
                    'seal_status_received' => null, // To be filled during physical receipt
                    'condition_received' => $sample->condition,
                    'received_at' => $sample->received_at ?? $request->received_at,
                    'received_by' => $receivedBy,
                ]);

                $created->push($evidenceUnit);
            }
        });

        return $created;
    }

    /**
     * Create a remaining unit for an evidence unit.
     *
     * @param  int  $evidenceUnitId  The evidence unit ID
     * @param  array  $data  Remaining unit data
     * @return RemainingUnit Created remaining unit
     */
    public function createRemainingUnit(int $evidenceUnitId, array $data): RemainingUnit
    {
        $evidenceUnit = EvidenceUnit::findOrFail($evidenceUnitId);

        $deliveredBy = $data['delivered_by'] ?? Auth::id();

        $remainingUnit = RemainingUnit::create([
            'evidence_unit_id' => $evidenceUnitId,
            'sample_code' => $evidenceUnit->sample_code, // Will be set by model if empty
            // remaining_code is auto-generated by model
            'qty_remaining' => $data['qty_remaining'] ?? null,
            'uom' => $data['uom'] ?? null,
            'seal_status_delivered' => $data['seal_status_delivered'] ?? null,
            'condition_delivered' => $data['condition_delivered'] ?? null,
            'delivered_at' => $data['delivered_at'] ?? now(),
            'delivered_by' => $deliveredBy,
            'handover_doc_no' => $data['handover_doc_no'] ?? null,
        ]);

        $this->syncSampleTestingQuantityFromRemainingUnits($evidenceUnit->fresh('sample', 'remainingUnits'));

        return $remainingUnit;
    }

    public function syncSampleTestingQuantityFromRemainingUnits(EvidenceUnit $evidenceUnit): void
    {
        $sample = $evidenceUnit->sample()->first();
        if (! $sample instanceof Sample) {
            return;
        }

        $deliveredQty = is_numeric($sample->package_quantity) ? (float) $sample->package_quantity : null;
        if ($deliveredQty === null) {
            return;
        }

        $totalRemainingQty = $evidenceUnit->remainingUnits()->sum('qty_remaining');
        $testingQty = max($deliveredQty - (float) $totalRemainingQty, 0.0);
        $uom = $evidenceUnit->remainingUnits()->orderBy('id')->value('uom');

        $sample->forceFill([
            'quantity' => $testingQty,
            'quantity_unit' => $uom ?: ($sample->unit ?? $sample->quantity_unit),
        ])->save();
    }

    public function reconcileSingleRemainingUnitsWithSampleQuantities(Collection $remainingUnits): Collection
    {
        if ($remainingUnits->isEmpty()) {
            return $remainingUnits;
        }

        if (! $remainingUnits instanceof EloquentCollection) {
            $remainingUnits = new EloquentCollection($remainingUnits->all());
        }

        $remainingUnits->loadMissing(['evidenceUnit.sample', 'evidenceUnit.remainingUnits']);

        $remainingUnits->each(function (RemainingUnit $remainingUnit): void {
            $evidenceUnit = $remainingUnit->evidenceUnit;
            if (! $evidenceUnit instanceof EvidenceUnit) {
                return;
            }

            if (($evidenceUnit->remainingUnits?->count() ?? 0) !== 1) {
                return;
            }

            $sample = $evidenceUnit->sample;
            if (! $sample instanceof Sample) {
                return;
            }

            $reconciledQty = $this->resolveRemainingQuantityFromSample($sample);
            if ($reconciledQty === null) {
                return;
            }

            $reconciledUom = $remainingUnit->uom ?: ($sample->unit ?? $sample->quantity_unit);
            $currentQty = is_numeric($remainingUnit->qty_remaining) ? (float) $remainingUnit->qty_remaining : null;

            if ($currentQty === $reconciledQty && $remainingUnit->uom === $reconciledUom) {
                return;
            }

            $remainingUnit->forceFill([
                'qty_remaining' => $reconciledQty,
                'uom' => $reconciledUom,
            ])->save();
        });

        return $remainingUnits;
    }

    /**
     * Get all evidence units for a request.
     */
    public function getEvidenceUnitsForRequest(int $requestId): Collection
    {
        return EvidenceUnit::with(['sample', 'receivedBy', 'remainingUnits'])
            ->where('request_id', $requestId)
            ->orderBy('sample_code')
            ->get();
    }

    /**
     * Ensure every sample in a request has an evidence label, then return the full set.
     */
    public function ensureEvidenceUnitsForRequest(int $requestId): Collection
    {
        $sampleIds = Sample::where('test_request_id', $requestId)
            ->orderBy('id')
            ->pluck('id')
            ->all();

        if ($sampleIds === []) {
            return collect();
        }

        $this->createEvidenceUnits($requestId, $sampleIds);

        return $this->getEvidenceUnitsForRequest($requestId);
    }

    /**
     * Get all remaining units for an evidence unit.
     */
    public function getRemainingUnitsForEvidence(int $evidenceUnitId): Collection
    {
        $remainingUnits = RemainingUnit::with(['deliveredBy', 'evidenceUnit.sample', 'evidenceUnit.remainingUnits'])
            ->where('evidence_unit_id', $evidenceUnitId)
            ->orderBy('created_at')
            ->get();

        return $this->reconcileSingleRemainingUnitsWithSampleQuantities($remainingUnits);
    }

    /**
     * Get all remaining units for a request (all samples).
     */
    public function getRemainingUnitsForRequest(int $requestId): Collection
    {
        $evidenceUnitIds = EvidenceUnit::where('request_id', $requestId)->pluck('id');

        $remainingUnits = RemainingUnit::with(['evidenceUnit.sample', 'evidenceUnit.remainingUnits', 'deliveredBy'])
            ->whereIn('evidence_unit_id', $evidenceUnitIds)
            ->orderBy('sample_code')
            ->orderBy('created_at')
            ->get();

        return $this->reconcileSingleRemainingUnitsWithSampleQuantities($remainingUnits);
    }

    /**
     * Auto-create remaining labels from delivered quantity minus testing quantity.
     *
     * Creates at most one automatic RemainingUnit per evidence unit and leaves
     * existing remaining labels untouched.
     */
    public function ensureAutoRemainingUnitsForRequest(TestRequest $request, ?int $actorId = null): void
    {
        $request->loadMissing(['investigator', 'samples', 'evidenceUnits.remainingUnits']);

        foreach ($request->samples as $sample) {
            $deliveredQty = is_numeric($sample->package_quantity) ? (float) $sample->package_quantity : null;
            $usedQty = is_numeric($sample->quantity) ? (float) $sample->quantity : null;

            if ($deliveredQty === null) {
                continue;
            }

            $leftoverQty = $usedQty !== null
                ? max($deliveredQty - $usedQty, 0.0)
                : $deliveredQty;

            if ($leftoverQty <= 0) {
                continue;
            }

            $evidenceUnit = $request->evidenceUnits
                ->firstWhere('sample_id', $sample->id)
                ?? EvidenceUnit::firstOrCreate(
                    ['sample_id' => $sample->id],
                    [
                        'request_id' => $request->id,
                        'receipt_code' => $request->receipt_number,
                        'sample_code' => $sample->sample_code,
                        'sample_type' => $sample->sample_category ?? $sample->sample_form,
                        'sample_desc' => $sample->short_description ?? $sample->sample_description,
                        'investigator_name' => $request->investigator?->name ?? $request->investigator?->rank_name,
                        'investigator_unit' => $request->investigator?->jurisdiction ?? $request->investigator?->satuan_kerja ?? $request->investigator?->unit,
                        'seal_status_received' => null,
                        'condition_received' => $sample->condition,
                        'received_at' => $sample->received_at ?? $request->received_at,
                        'received_by' => $sample->received_by ?? $actorId,
                    ]
                );

            if (RemainingUnit::where('evidence_unit_id', $evidenceUnit->id)->exists()) {
                $this->reconcileSingleRemainingUnitsWithSampleQuantities(
                    $evidenceUnit->remainingUnits()->with(['evidenceUnit.sample', 'evidenceUnit.remainingUnits'])->get()
                );

                continue;
            }

            RemainingUnit::create([
                'evidence_unit_id' => $evidenceUnit->id,
                'sample_code' => $sample->sample_code,
                'qty_remaining' => $leftoverQty,
                'uom' => $sample->unit ?? $sample->quantity_unit,
                'seal_status_delivered' => 'disegel',
                'delivered_at' => now(),
                'delivered_by' => $actorId,
            ]);
        }
    }

    private function resolveRemainingQuantityFromSample(Sample $sample): ?float
    {
        $deliveredQty = is_numeric($sample->package_quantity) ? (float) $sample->package_quantity : null;
        if ($deliveredQty === null) {
            return null;
        }

        $usedQty = is_numeric($sample->quantity) ? (float) $sample->quantity : null;

        return $usedQty !== null
            ? max($deliveredQty - $usedQty, 0.0)
            : $deliveredQty;
    }

    /**
     * Log a print action.
     */
    public function logPrint(
        string $labelType,
        $printable,
        string $format = 'a4',
        ?string $reason = null,
        int $count = 1
    ): LabelPrintLog {
        $printedBy = Auth::id();

        return LabelPrintLog::logPrint(
            $labelType,
            $printable,
            $printedBy,
            $format,
            $reason,
            $count
        );
    }

    /**
     * Get print history for a printable item.
     */
    public function getPrintHistory($printable): Collection
    {
        return $printable->printLogs()
            ->with('printedBy')
            ->orderByDesc('created_at')
            ->get();
    }
}
