<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Investigator>
 */
class InvestigatorFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'rank' => fake()->randomElement(['IPDA', 'IPTU', 'AKP', 'AKBP', 'Kompol', 'AIPDA', 'AIPTU', 'Brigadir', 'Bripka', 'Briptu']),
            'nrp' => fake()->unique()->numerify('##########'),
            'jurisdiction' => fake()->randomElement(['Polda Metro Jaya', 'Polres Jakarta Pusat', 'Polres Jakarta Barat', 'Polres Jakarta Timur', 'Polres Jakarta Selatan', 'Polres Jakarta Utara']),
            'phone' => fake()->phoneNumber(),
            'email' => fake()->unique()->safeEmail(),
            'address' => fake()->address(),
            // Note: folder_key is auto-generated by the model's boot() method (NRP + slug of name)
        ];
    }
}
