<?php

return [
    'enabled' => (bool) env('GOWA_UPDATER_ENABLED', false),
    'no_socket_gate' => (bool) env('GOWA_UPDATER_NO_SOCKET_GATE', false),
    'catalog_path' => env('GOWA_UPDATER_CATALOG_PATH', '/etc/lpmf/gowa-updater/catalog.json'),
    'catalog_public_key_path' => env('GOWA_UPDATER_CATALOG_PUBLIC_KEY_PATH', '/etc/lpmf/gowa-updater/catalog.pub'),
    'submit_helper' => env('GOWA_UPDATER_SUBMIT_HELPER', '/usr/local/sbin/lpmf-gowa-submit'),
    'sudo_binary' => env('GOWA_UPDATER_SUDO_BINARY', '/usr/bin/sudo'),
    'runner_path' => env('GOWA_UPDATER_RUNNER_PATH', '/usr/local/libexec/lpmf-gowa-runner'),
    'capability_manifest' => env('GOWA_UPDATER_CAPABILITY_MANIFEST', '/etc/lpmf/gowa-updater/capability.json'),
    'rollback_manifest' => env('GOWA_UPDATER_ROLLBACK_MANIFEST', '/etc/lpmf/gowa-updater/rollback-manifest.json'),
    'authority_path' => env('GOWA_UPDATER_AUTHORITY_PATH', '/etc/lpmf/gowa-updater/authority.json'),
    'preflight_gate' => env('GOWA_UPDATER_PREFLIGHT_GATE', '/etc/lpmf/gowa-updater/preflight.pass'),
    'enabled_marker' => env('GOWA_UPDATER_ENABLED_MARKER', '/etc/lpmf/gowa-updater/enabled'),
    'runtime_evidence_path' => env('GOWA_UPDATER_RUNTIME_EVIDENCE_PATH', '/var/lib/lpmf/gowa-updater/runtime.json'),
    'evidence_root' => env('GOWA_UPDATER_EVIDENCE_ROOT', '/var/lib/lpmf/gowa-updater/evidence'),
    'evidence_public_key_path' => env('GOWA_UPDATER_EVIDENCE_PUBLIC_KEY_PATH', '/etc/lpmf/gowa-updater/evidence.pub'),
    'evidence_retention_days' => (int) env('GOWA_UPDATER_EVIDENCE_RETENTION_DAYS', 30),
    'lease_minutes' => (int) env('GOWA_UPDATER_LEASE_MINUTES', 10),
    'policy_version' => env('GOWA_UPDATER_POLICY_VERSION', '1'),
    'required_capability_version' => env('GOWA_UPDATER_REQUIRED_CAPABILITY_VERSION', '1'),
    'database_name' => env('GOWA_UPDATER_DATABASE', env('DB_DATABASE')),
    'submit_role' => env('GOWA_UPDATER_SUBMIT_ROLE', 'lpmf_gowa_submit'),
    'update_unit_prefix' => env('GOWA_UPDATER_UPDATE_UNIT_PREFIX', 'lpmf-gowa-update@'),
    'lock_path' => env('GOWA_UPDATER_LOCK_PATH', '/run/lpmf/gowa-updater/update.lock'),
    'request_root' => env('GOWA_UPDATER_REQUEST_ROOT', '/var/lib/lpmf/gowa-updater/requests'),
];
